# Generated by Django 4.2.14 on 2025-02-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheetapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spreadsheet',
        ),
    ]
