# Generated by Django 4.2.19 on 2025-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spreadsheetapp', '0002_delete_spreadsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheetapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
